### ISSUE TITLE
コンテンツ要素の実装1(内容はnoteを参照)

### ISSUE THREAD

**Issue by Minizu424** [toho-festival/website-2021#3]
4/24(本日までに完成)
- 一番上の写真部分の作成
  - 「tohofes70th」と「日程」はDOM内に記述
- 体験型企画などの企画部門(六角形)を作成　計３つ
- [ ] スマホとパソコンで整合性の取れたものにする

**Comment by Sarami67** [comment]
4/24　
大場が作業を開始します
